defaults:
  - _self_
  - data: gtsrb
  - model: tinycnn
  - training: trainConf

paths:
  models: "models"

ckpt_path: "models/latest/best_model.pth"
figures_path: "reports/figures"
image_size: [64, 64]

wandb:
  project_name: "gtsrb_classification"
  team_name: "5m"

data:
  gcs:
    bucket: "traffic_sign_data"
    prefix: "dataset"
